configfile: "config.yaml"

DATASETS = list(config["datasets"].keys())

def get_recordings(wildcards):
    print(config["datasets"][wildcards.dataset])
    return config["datasets"][wildcards.dataset]["path"]

# Define score metrics 
CLF_METRICS = ["Accuracy", "Precision", "Recall", "F1-score"]
ERRORS = ["MSE", "MAE", "RMSE"]


# Main rule that defines the final outputs of the workflow
rule all:
    input:
        expand("results/classification_split/{metric}.csv", metric=CLF_METRICS)
        

# Rule to collect and aggregate classification scores from all datasets
rule collect_classification_scores:
    input:
        scores=expand("workflow_output/results/classification_svm/{dataset}_classification_scores.pkl", dataset=DATASETS)
    output:
        ["results/classification_split/{}.csv".format(metric) for metric in CLF_METRICS]
    script:
        "scripts/collect_scores.py"


# Rule to perform classification using various feature sets and classifiers
rule classification:
    input:
        spikes=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_spikes.pkl",
        features_ss_spdf=lambda wildcards: f"workflow_output/features/{wildcards.dataset}_features_ss_spdf.pkl",
        features_simple=lambda wildcards: f"workflow_output/features/{wildcards.dataset}_features_simple.pkl",
        features_raw=lambda wildcards: f"workflow_output/features/{wildcards.dataset}_features_raw.pkl",
        templates=lambda wildcards: f"workflow_output/templates/{wildcards.dataset}_ap_templates.pkl"
    output: 
        classification_results="workflow_output/results/classification_svm/{dataset}_classification_scores.pkl",
    params:
        name=lambda wildcards: config["datasets"][wildcards.dataset]["name"],
    script:
        "scripts/classification.py"

# Rule to extract various types of features from preprocessed spike data
rule feature_extraction:
    input:
        raw_data=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_raw_data.pkl",
        spikes=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_spikes.pkl",
        ap_derivatives=lambda wildcards: f"workflow_output/pre_processing/{wildcards.dataset}_ap_derivatives.pkl",
        ap_track_window_m=lambda wildcards: f"workflow_output/pre_processing/{wildcards.dataset}_ap_track_window_modified.pkl",
        ap_window_iloc=lambda wildcards: f"workflow_output/pre_processing/{wildcards.dataset}_ap_window_iloc.pkl"
    output:
        features_ss_spdf="workflow_output/features/{dataset}_features_ss_spdf.pkl",
        features_simple="workflow_output/features/{dataset}_features_simple.pkl",
        features_raw="workflow_output/features/{dataset}_features_raw.pkl",
        length_df="workflow_output/spike_numbers/{dataset}_length_df.csv",
        simple_features_figure="workflow_output/features/figures/{dataset}_simple_features.png",
        ss_spdf_features_figure="workflow_output/features/figures/{dataset}_ss_spdf_features.png"
    params:
        use_bristol_processing=lambda wildcards: config["datasets"][wildcards.dataset]["flags"]["use_bristol_processing"],
        name=lambda wildcards: config["datasets"][wildcards.dataset]["name"]
    script:
        "scripts/feature_extraction.py"

# Rule to compute template similarity errors for spike templates
rule template_similarity:
    input:
        ap_templates=lambda wildcards: f"workflow_output/templates/dataframes/{wildcards.dataset}_ap_templates.pkl"
    output:
        template_similarity= "results/template_similarity_errors/{dataset}_template_similarity.pkl"
    script:
        "scripts/compute_template_errors.py"

# Rule to create spike templates and apply filtering to the data
rule template_and_filtering:
    input:
        raw_data=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_raw_data.pkl",
        ap_derivatives=lambda wildcards: f"workflow_output/pre_processing/{wildcards.dataset}_ap_derivatives.pkl",
        ap_track_window=lambda wildcards: f"workflow_output/pre_processing/{wildcards.dataset}_ap_track_window.pkl",
        ap_window_iloc=lambda wildcards: f"workflow_output/pre_processing/{wildcards.dataset}_ap_window_iloc.pkl",
        spikes=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_spikes.pkl"
    output:
        ap_track_window_m="workflow_output/pre_processing/{dataset}_ap_track_window_modified.pkl",
        ap_templates="workflow_output/templates/{dataset}_ap_templates.pkl",
        template_figure="workflow_output/templates/figures/{dataset}_templates.png",
        waveform_figure="workflow_output/templates/figures/{dataset}_waveforms.png"
    params:
        use_bristol_processing=lambda wildcards: config["datasets"][wildcards.dataset]["flags"]["use_bristol_processing"]
    script:
        "scripts/templates_and_filtering.py"

# Rule to preprocess the raw data, including windowing and derivative calculations
rule pre_process_data:
    input:
        raw_data=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_raw_data.pkl",
        stimulations=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_stimulations.pkl",
        spikes=lambda wildcards: f"workflow_output/dataframes/{wildcards.dataset}_spikes.pkl"
    output: 
        ap_window_iloc="workflow_output/pre_processing/{dataset}_ap_window_iloc.pkl",
        ap_derivatives="workflow_output/pre_processing/{dataset}_ap_derivatives.pkl",
        ap_track_window="workflow_output/pre_processing/{dataset}_ap_track_window.pkl",
    params:
        name=lambda wildcards: config["datasets"][wildcards.dataset]["name"],
        path_dapsys=lambda wildcards: config["datasets"][wildcards.dataset]["path_dapsys"],
        use_bristol_processing=lambda wildcards: config["datasets"][wildcards.dataset]["flags"]["use_bristol_processing"],
    script:
        "scripts/pre_processing.py"

# Rule to read in raw data from various formats and convert to standardized nix format
rule read_in_data:
    input:
        get_recordings
    output: 
        raw_data="workflow_output/dataframes/{dataset}_raw_data.pkl",
        stimulations="workflow_output/dataframes/{dataset}_stimulations.pkl",
        spikes="workflow_output/dataframes/{dataset}_spikes.pkl",
        nix_file= "datasets/nix/{dataset}.nix",
    params:
        name=lambda wildcards: config["datasets"][wildcards.dataset]["name"],
        path_dapsys=lambda wildcards: config["datasets"][wildcards.dataset]["path_dapsys"],
        path_nix=lambda wildcards: config["datasets"][wildcards.dataset]["path_nix"],
        use_bristol_processing=lambda wildcards: config["datasets"][wildcards.dataset]["flags"]["use_bristol_processing"],
        time1=lambda wildcards: config["datasets"][wildcards.dataset]["time1"],
        time2=lambda wildcards: config["datasets"][wildcards.dataset]["time2"],
        tracks_to_ignore=lambda wildcards: config["datasets"].get(wildcards.dataset, {}).get("tracks_to_ignore", [])
    script:
        "scripts/read_in_data.py"
